version: "3.3"

services:
  mariadb_service:
      context: .
      dockerfile: Dockerfile
    image: mariadb
    ports:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "True"
    restart: unless-stopped
    volumes:
      - "./baseball.sql:./baseball.sql"

  rolling_average_service:
    depends_on:
      - mariadb_service
    build:
      context: .
      dockerfile: Dockerfile
    image: maria_db
    ports:
      - "8080"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="True"
    restart: unless-stopped
    
